version: '3.8'

services:
  rocketchat:
    platform: linux/amd64
    image: rocketchat/rocket.chat:6.9.2
    environment:
      - TEST_MODE=true
      - EXIT_UNHANDLEDPROMISEREJECTION=true
      - 'MONGO_URL=${MONGO_URL}'
      - OVERWRITE_SETTING_Log_Level=2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - mongo
    ports:
      - '3000:3000'

  mongo:
    image: docker.io/bitnami/mongodb:7.0
    restart: on-failure
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongo}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongo}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
