name: Close inactive issues
on:
  schedule:
    - cron: '0 0 20 * *'
jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 14.21.3
          cache-modules: true
          install: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: rharkor/caching-for-turbo@v1.5

      - name: Build packages
        run: yarn build

      - name: 'Start release candidate'
        uses: ./packages/release-action
        with:
          action: next
          base-ref: develop
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
